version: "3.2"
services:
  ch-server-1:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros1.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/1:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros2.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/2:/var/lib/clickhouse
    ports:
      - 8124:8123
      - 9001:9000
  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macros3.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/3:/var/lib/clickhouse
    ports:
      - 8125:8123
      - 9002:9000
  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
